name: locations_work
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  camera: ^0.10.3+2
  country_code_picker: ^3.0.0
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  date_picker_timetable: ^0.0.2
  dio: ^5.0.2
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^13.0.0
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  path: ^1.8.2
  path_provider: ^2.0.13
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.0.18
  solid_lints: ^0.0.14
  sqflite: ^2.2.6
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/available_time.json
    - assets/images/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
