import 'package:flutter/material.dart';
import 'package:locations_work/core/routes/app_routes.dart';
import 'package:locations_work/core/utils/my_icons_manager.dart';
import 'package:locations_work/modules/just_example/widgets/just_select_row.dart';

class JustExample1 extends StatelessWidget {
  const JustExample1({super.key});

  @override
  Widget build(BuildContext context) {
    String? isButton1Selected;
    return Scaffold(
      appBar: AppBar(),
      body: StatefulBuilder(builder: (context,setState){
        return ListView(
          padding: const EdgeInsets.all(20),
          children: [
            JustSelectRow(
              onButtonPressed: (buttonSelected) {
                setState((){
                  isButton1Selected = buttonSelected;
                  debugPrint(buttonSelected);
                });
              },
            ),
            const SizedBox(height: 10),
            Center(
              child: isButton1Selected == 'Button 1' || isButton1Selected == null
                  ? const Text('Button 1',style: TextStyle(fontSize: 17,color: Colors.blueGrey),)
                  : const Text('Button 2',style: TextStyle(fontSize: 17,color: Colors.blueGrey),),
            ),
            const SizedBox(height: 10),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.add,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.airplay,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.alert_octagon,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.alert_triangle,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.align_center,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.align_justify,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.align_left,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.align_right,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.alter_circle,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.andriod_line,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.android_battery,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.android_internet,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.android_network,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.apple,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.archive,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.archive_input,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_down,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_down_circle,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_down_left,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_down_right,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_left_cirlce,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_right,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_right_cricle,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_up,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_up_circle,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_up_left,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.arrow_up_right,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.award,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.bagger,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.bagger_add,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.bagger_removed,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.bar_chart,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.bar_chart_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.barcode,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.barcode_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.battery,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.battery_charging,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.battery_full,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.bell,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.block,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.book,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.book_open,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.book_open_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.briefcase,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.browser,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.bug,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.calculator,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.calendar,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.camera,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.camera_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_add,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_cart,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_check,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_discount,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_error,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_error_1,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_favorite,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_removed,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cart_search,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.cast,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.category,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.chat,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.check_circle,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.check_square,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.chevrons_down,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.chevrons_left,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.chevrons_right,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.chevrons_up,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.clipboard,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.clock,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.close,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.code,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.code_dot,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.compass,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.components,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.copy,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.credit_card,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.delivery_hall,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.discord,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.discount,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.discount_1,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.dot,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.download,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.draft,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.dropdown,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.dynamiclayers,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.figma,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.figma_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.file_add,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.file_move,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.filter,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.fold,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.full_screen,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.germany,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.gift,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.google,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.home,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.information,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.instagram,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.internet,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.invisible,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.iOS_network,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.iOS_wlan,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.link,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.listen,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.loading,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.lock_close,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.lock_open,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.mail,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.map,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.market,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.marketing,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.master_card,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.menu,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.microphone,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.more,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.package,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.paypal,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.pin,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.play,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.progress,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.propertie,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.qr_code,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.radio_button_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.repeat,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.return1,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.rotate,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.search,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.settings,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.settings_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.Share,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.shipment,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.shipment_truck,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.shopping_bag,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.shopping_basket,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.shopping_card,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.shopping_cart_add,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.shopping_cart_remove,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.slack,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.sort_by,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.spam,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.split_screen,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.spotify,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.structure,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.sun,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.support,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.trash,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.turn,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.undone,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.upload,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.user,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.verified,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.video,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.video_2,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.video_3,size: 60,color: Colors.orange,),),
            Padding(padding: const EdgeInsets.symmetric(vertical: 4.0), child: Icon(MobileToolkit.visible,size: 60,color: Colors.orange,),),
            const SizedBox(height: 10),
            TextButton(onPressed: (){
              Navigator.of(context).pushNamed(Routes.justExample2Route);
            }, child: const Text('to just Example 2'))
          ],
        );
      },)
    );
  }
}
